//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterPEANE
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Register
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_Register()
        {
            this.t_User = new HashSet<t_User>();
        }
    
        public string FullName { get; set; }
        public string Mobile { get; set; }
        public byte[] PicProfile { get; set; }
        public string Prog_lang { get; set; }
        public System.Guid Register_ID { get; set; }
        public string createdBy { get; set; }
        public System.DateTime createdDAte { get; set; }
        public string PicProfileName { get; set; }
        public string PicProfileNameExt { get; set; }
        public int isShowMobile { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_User> t_User { get; set; }
    }
}
