//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterPEANE
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_User
    {
        public System.Guid UserID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<System.Guid> RegisterID { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
    
        public virtual t_Register t_Register { get; set; }
        public virtual t_UserLogin t_UserLogin { get; set; }
    }
}
